### ISSUE TITLE
Create CRUD utils to work with company evaluations

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#12]
## Tasks ✅ 

- [x] Create crud.py to wrap the functions 🧰 
- [x] Create a function to get a company evaluation by ID 🔧 
- [x] Create a function to create a company evaluation 🔧
