### ISSUE TITLE
Fix: 

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#14]
## Tasks 🔥 

- [x]  add `from . import database` in ratings/config/__init__.py to allow us to access database.py file

## CompanyEvaluation model 🔧 

- [x] Change the type of column of company_id to **Integer**
- [x] Change the type of column of start_date and end_date to **Date**
- [x] Change the type of column of is_still_working_here to **Integer**
- [x] Change the type of column of recommended_a_friend, is_legally_company, utility_counter, utility_counter, non_utility_counter to **Integer** 
- [x] Change the name of remote_work_allowed to allows_remote_work to get consistency between the model and the database
- [x] Add a comment in the class to get the difference between the model and the schemas 

## CompanyEvaluation schema 
- [x] Add a comment in the schemas to get the difference between the chema and the model
- [x] Add the attribute company_id in CompanyEvaluationBase
- [x] Add currency_type, salary_frequency to CompanyEvaluationCreate
- [x] Change the type of the attributes start_date and end_date to **date**
