### ISSUE TITLE
Create Path operations

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#17]
## Tasks 🧑‍🏭 

- [x] Crete a path operation to create a company evaluation
- [x] Crete a path operation to get a company evaluation by id
- [x] Create a path operation to get a list of company evaluation by company_id
- [x] Add Path parameter validations
- [x] Change the parameter id in crud of get company evaluation by id
