### ISSUE TITLE
Create flowchart to create applicants in code 🏋️

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#20]
## Task 🦾 

- [x] Create the SQLAlchemy model in the file model.py
- [x] Create the Pydantic schemas ApplicantBase, ApplicantCreate, Applicant.
- [x] Create the functionality crud to save one applicant
- [x] Create the path operation to save applicants
- [x] Apply path operation validation
- [x] apply path operation body
- [x] add return status code
