### ISSUE TITLE
Create flowchart to store and applicant evaluation

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#21]
## Task 🦾 

- [x] Create the SQLAlchemy model for ApplicantEvaluation in the file model.py
- [x] Add SQLAlchemy relationship between applicant and applicant evaluation
- [x] Create the Pydantic schemas ApplicantEvaluationBase, ApplicantEvaluationCreate, ApplicantEvaluation.
- [x] Create the functionality crud to save  Applicant Evaluations
- [x] Create the path operation of the Applicant Evaluations
- [x] Apply path operation validation
- [x] apply path operation body
- [x] add return status code
- [x] Try the path operation with the datable and save information
