### ISSUE TITLE
List of Reporting Reason Types

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#33]
## Task 🏁 
- [x] create a path operation which retrieve reporting reason types catalog to allow the user to select  the name of the reason
- [x] Create model to ReportingReasonType
- [x] Create the schema ReportingReasonTypeBase
- [x] Create the schema ReportingReasonTypeCreate
- [x] Create the schema ReportingReasonTypeOut
