### ISSUE TITLE
Refactor code with standard pep 8

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#42]
## Tasks 🧑‍🏭 

- [ ] Rename path operations
- [ ] organize the parameter in the functions
- [ ] apply spaces in functions
- [ ] Fix typos
