### ISSUE TITLE
Enhance company evaluation flow with a request to companies

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#45]
## Tasks:

- [x] Create a function check_company_id_exist in crud.py to solve the problem to insert a company evaluation
- [x] Load the url from a enviroment variable
- [x] Add an if sentence before inserting a company evaluation to check if exist and if not raise an error
