### ISSUE TITLE
Create the functionality to register applicants

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#56]
## Tasks 🧑‍🏭 

- [x] Create model applicants
- [x] Create model recruitment process evaluation
- [x] create a function to generate a tracking_code
- [x] Create the path operation to allow pdf files for the cv and the motivation letter
