### ISSUE TITLE
Create functionality to attach an applicant evaluation.

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#58]
## Tasks

- [x] Create model
- [x] create schema
- [x] create path operation
- [x] validate that applicant id exist
- [ ] Validate that the company id exist
