### ISSUE TITLE
Create the user functionality to create a recruitment process evaluation

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#60]
## Tasks 🦾 

- [ ] Create model recruitmentProcessEvaluation
- [ ] Create schemas [base, create, out] to recruitmentProcessEvaluation
- [ ] create the path operation post
- [ ] validate applicant existence 
- [ ] Validate company existence
