### ISSUE TITLE
Create Filter

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#62]
## Tasks ✅ 

- [x] Create job_title filter
- [x] create content_type filter
- [x] Create job_location filter
- [x] Create date filter
- [x] create helpfulness filter
