### ISSUE TITLE
Integración relación con status tabla y agregar campo vacancy_id

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#72]
## Tasks ☑️ 

Add vacancy_id in:

- [x] Agregar vacancy id como atributo del fomrulario
- [x] Agregarlo al schema
- [x] agregarlo al crud 
- [x] validar que no se pueda iniciar el proceso de crear un applicante si la vacante no existe
- [x] create a function to check if a vacancy exist and create the applicant

## tasks postulation_status
- [x] Create the table status en sql
- [x] configurar relación de aplicantes con status
- [x] crear schemas base / create / out de status
- [x] crear path operation para retornar  un listado de status
- [x] Agregar validaciones a path operation que si no hay aplicant status retornar un []
