### ISSUE TITLE
Create endpoint to check the application status of one applicant

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#77]
## Tasks ☑️ 

- [x] Validate path parameter traking_code like a string and max_length 8 required
- [x] Validate path paarmeter paternal_last_name like str and max_legth 70 required
- [x] Add response model ApplicantOut and status code 200
- [x] add a function get applicant process passing like parameter a session of th database and the path parameter
- [x] create a crud functionality to get the applicant wich tracking code and the paternal_last_name be equal like the path parameters
