### ISSUE TITLE
SSL Integrations

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#87]
## Tasks ☑️ 

- [x] Add a folder compose to separate the docker's file for every environment local and production and add Nginx and the database
- [x] Create a docker file to Nginx and create one the file of configuration for run Nginx with my project
- [x] create a directory to add the Auth file of Zero SSL
- [x] Create a production .yml to run in the ec2 instance
- [x] configurate Ngnix to expose the port 443
