### ISSUE TITLE
Cretae the function to return the rating of company evaluations

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#89]
## Tasks ☑️ 

- [x] Add the attribute rating in sql, models, schemas, and crud
- [x] create a function to assign_weight() to receive the value a company evaluation criteria a return the weight assigned
- [x] Create a function def calculate_company_evaluation_average(*args)  which is going to receive n numbers of parameters and calculate the average by the numbers of criteria.
- [x] Add order by ratings DESC ASC like a query parameter
