### ISSUE TITLE
Load company evaluations an general ratings in in the feneral_ratings endpoint

### ISSUE THREAD

**Issue by javieramayapat** [Platzi-Master-C8/gethired-jobplacement-ratings-backend#91]
## Tasks ☑️ 

- [ ] Create a function to get the information of a company by ID
- [x] Create a function to return the number of company evaluations created
- [x] Create a function to calculate the general rating for company criteria7
- [ ] Combine all this information in company evaluation endpoint
